### ISSUE TITLE
Error appears when trying to convert file to using Markdown (Liquid)

### ISSUE THREAD

**Issue by legion80** [braver/sublime-liquid#8]
I manually installed [Liquid-2.1.0-st4134.sublime-package](https://github.com/SublimeText/Liquid/releases/download/2.1.0/Liquid-2.1.0-st4134.sublime-package)

In Sublime Text 4 (4143), trying to convert a file to Markdown (Liquid) I get this error:

Error loading syntax file "Packages/Liquid/Syntaxes/Markdown (Liquid).sublime-syntax": Error in regex: end pattern with unmatched parenthesis in regex \s+(and|or|not|contains|(\!\=|\=\=|<\=|>\=|<|>)\s+

**Comment by deathaxe** [comment]
Did you rename the package file to `Liquid.sublime-package`as instructed in manual install guide?

> 2. Rename it to Liquid.sublime-package

**Comment by legion80** [comment]
I did. It still failed.

I tried removing that package, and another Liquid Syntax-related package, then reinstalled it, and that seemed to fix it. Sorry for the noise!
